# Generated by Django 3.2.14 on 2022-07-05 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('addressCabinet', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Adresse du cabinet')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
