# Generated by Django 3.2.14 on 2022-07-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addressCabinet',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Adresse du cabinet'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Description'),
        ),
    ]
