# Generated by Django 3.2.14 on 2022-07-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20220704_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addressCabinet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
    ]
